### ISSUE TITLE
(Grafana Labs) Loki 검증

### ISSUE THREAD

**Issue by robertchoi80** [openinfradev/decapod-issues#31]
**내용**
Admin Cluster 등의 환경에 lightweight한 로깅 시스템 구축을 위해 Loki 를 검증한다
 - 효용성: 운영자가 grafana dashboard 에서 어떤 작업들을 할수 있는가?  대시보드 구성은 수월한가?
 - 배포형상: collector는 그대로 fluentbit 사용 가능한가??  그럴 경우 설정 방법은???
 - 안정성 및 확장성 등

**산출물**
- Wiki page 정리

**Comment by robertchoi80** [comment]
처음에 개념 파악 차원에서 살펴본 포스팅
https://jerryljh.tistory.com/m/20?category=867665

helm chart로 LOKI + promtail 설치 후 Grafana dashboard의 Explore 메뉴에서 이리저리 로그 검색해봄 (다음 cheet sheet 참고)
https://megamorf.gitlab.io/cheat-sheets/loki/
https://grafana.com/docs/loki/latest/logql/

Loki sample dashboard import해서 테스트해 보니 (drop-down 형태로) namespace, pod 명으로 필터링해서 로그 검색은 가능함.
https://grafana.com/blog/2020/04/08/loki-quick-tip-how-to-create-a-grafana-dashboard-for-searching-logs-using-loki-and-prometheus/

이때, 필터링 조건을 만드는 데 사용되는 label_values function에 대한 설명
https://banzaicloud.com/blog/grafana-templating/

---
여기까지 느낀 점은, 기본적인 로그 검색은 가능하지만 kibana 를 쓰는 것에 비해 UI가 많이 불편한 것 같습니다
Kibana의 경우 각각의 field를 column 형태로 구분해서 일목요연하게 볼 수 있었는데, Grafana에선 그런 부분이 불가능해보입니다.
상단의 duration 설정을 바꿔도 잘 적용이 안되는 문제도 있고, 부족한 부분들이 좀 보입니다.

**Comment by robertchoi80** [comment]
**Fluentbit 연동 테스트 상황**

fluentbit output 설정 매뉴얼
https://docs.fluentbit.io/manual/pipeline/outputs/loki

이건 grafana 진영에서 만든 플러그인인 듯…
https://grafana.com/docs/loki/latest/clients/fluentbit/

fluentbit-operator 의 sample config
https://github.com/fluent/fluentbit-operator/blob/master/config/samples/logging_v1alpha2_output.yaml

가장 위의 fluentbit 문서를 참고하여 loki향 output 을 추가했는데, 제대로 로그 전송이 되지 않고 있음.
```
$ kubectl get output -n lma fluentbit-output-loki -o yaml
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
...
spec:
  loki:
    autoKubernetesLabels: true
    host: loki.default
    lineFormat: json
    name: grafana-loki
    port: 3100
  match: '*'
```

fluentbit 버전을 확인해보니, 1.6 이상에서 Loki plugin이 추가된 듯 보여서 이미지 버전 업그레이드가 필요할 것 같음
현재 사용 중인 이미지는 성일님이 만든 이미지인데 어떤 내용이 추가된 건지 확인이 필요함.

- siim/fluent-bit-for-operator:v1.4.6

**Comment by robertchoi80** [comment]
성일님과 통화 후 upstream 이미지에서 몇가지 버그가 있어 수정하신 거라고 들었는데, 시간이 많이 지났으니 fix되었을 가능성을 고려하여 다시 upstream 최신 버전 테스트해보기로 함. 

이미지 버전만 올리니 몇가지 에러가 발생하여, fluentbit 및 fluentbit-operator까지 전부 cleanup하고, 다시 설치하였는데, loki 쪽으로 로그가 전혀 전달되지 않음. 
input, output CR을 추가해도 operator 자체에서 로그도 없고 반응이 없는 듯 보임.  계속 삽질하다가 결국 코드까지 봤더니, 원래 reconcile시 각 output에 대해 별도 로그를 출력하지 않고, config도 개별 output이 아닌 통째로 한 파일로 만들어 pod에 mount하게 되어있음. 그런데 config의 mount path가 default config path와 다른 걸 발견하고, 결국 이미지가 다른 것도 발견함.
- fluent/fluenctbit 대신 kubesphere/fluentbit 을 사용해야 함 

이미지 교체 후 loki pod에 관련 로그가 찍히기 시작하는데, entry out of order 에러가 계속 발생.
```
level=warn ts=2021-11-12T03:13:36.124864051Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=258.49µs err="rpc error: code = Code(400) desc = entry with timestamp 2021-11-12 03:13:04.434475529 +0000 UTC ignored, reason: 'entry out of order' for stream: {job=\"fluent-bit\"},\ntotal ignored: 1 out of 1" msg="gRPC\n"
```

구글링을 아무리 해봐도, 복수개의 pod에서 동일 label set으로 로그를 보내다보니 timestamp가 섞여서 오류를 내는 것이고, 그에 대한 해결책으로 각 pod가 서로 명확히 구분되도록 label set을 unique하게 만들라는 답변이 대부분임. 그렇지 않은 경우에 대해세는 특별한 해결책이 제시되지 않음.   

이에 대한 complain이 많았는지 loki 2.4 부터는 out-of-order를 허용하는 option이 추가되었음.
https://grafana.com/blog/2021/09/16/avoid-dropped-logs-due-to-out-of-order-timestamps-with-a-new-loki-feature/

하지만 2.4 버전 돌려보면 다음 에러와 함께 crash됨.
```
level=error ts=2021-11-12T09:11:05.198522035Z caller=log.go:106 msg="error running loki" err="mkdir wal: read-only file system\nerror initialising module: ingester\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581
```

위 에러 관련하여 이슈 리포트 및 PR이 있는데, 아래 내용들 merge되고, 2.4 버전이 사용 가능해지면 다시 테스트해보려 함.
https://github.com/grafana/loki/issues/4704
https://github.com/grafana/loki/pull/4705

**Comment by robertchoi80** [comment]
위의 PR이 merge되어서, 최신 버전의 Loki 이미지 사용하니 에러 메세지가 좀더 명확해졌음. 
그래서 loki chart의 config 에서 아래 내용 수정 반영하여 다시 배포함
```
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    wal:
      dir: /data/wal   # 쓰기 권한이 있는 경로로 지정
...

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    unordered_writes: true   # out-of-order 허용하도록 설정
```

debut 모드로 fluentbit 로그를 보니 container 로그 파일에 제대로 access를 못하고 있음
```
[2021/11/17 06:51:15] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /var/log/containers/aler
tmanager-lma-alertmanager-0_lma_alertmanager-bee721edd96b297614308334b2849dee972d98886494c915d5ce15a48
62d45fa.log, inode 93512925
...
```

분명 실제로 존재하는 파일인데, 확인해보니 root 권한으로만 access가 가능하게 되어있음.  위 파일은 몇번의 링크를 거쳐 최종적으로 /var/lib/docker/containers 아래의 로그 파일을 가리키게 되어있는데,  해당 폴더 권한이 700 으로 되어있어서 0755 로 변경해주었음. 

다시 fluentbit pod를 재시작해보면 로그 파일은 제대로 읽는 것 같지만, 'entry too far behind' 라는 새로운 에러가 발생함
결국 out-of-order 에서 far-behind로 종류만 바뀐 셈ㅠ
```
[2021/11/19 01:42:54] [debug] [input:tail:tail.0] scanning path /var/log/containers/*.log
[2021/11/19 01:42:54] [debug] [input:tail:tail.0] inode=88644700 with offset=106 appended as /var/log/containers/alerted-log-exporter-5b464f985d-75r9g_lma_exporter-cbbcf28981fd9126dbe28e29c08fc45f915122077120a96972417312ad7ba41d.log
[2021/11/19 01:42:54] [debug] [input:tail:tail.0] scan_glob add(): /var/log/containers/alerted-log-exporter-5b464f985d-75r9g_lma_exporter-cbbcf28981fd9126dbe28e29c08fc45f915122077120a96972417312ad7ba41d.log, inode 88644700

[2021/11/19 01:43:04] [error] [output:loki:loki.0] loki.default:3100, HTTP status=400 Not retrying.
entry with timestamp 2021-11-18 14:20:48.330910601 +0000 UTC ignored, reason: 'entry too far behind' for stream: {job="fluent-bit"},
total ignored: 1 out of 1
...
```

관련 이슈 리포트가 있는데, 아직 답은 없는 상태임.  
https://github.com/grafana/loki/issues/4694

아직 fluentbit 과 loki 연동은 많이 불안정한듯 하여, 여기서 중단하겠음.   그냥 promtail 쓰는게 좋을 듯 합니다.

**Comment by robertchoi80** [comment]
많은 pod label 중에 host 정보는 포함되지 않아 scrape_config 설정 부분을 분석해보다보니, host명을 임시 label로만 처리하고 버리게 되어있음
```
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
```
여기서 __host__를 host 로 변경하면 실제 label 로 사용이 되고, loki에도 잘 보여지는 것을 확인하였습니다.

**Comment by robertchoi80** [comment]
맡은 업무 중 위의 host label 추가 건을 어떻게 helm chart에 반영할 수 있는지 보았더니, 부분적인 수정은 불가능하고 결국 scrape_config 전체를 override해야 하는 구조임.
```
apiVersion: v1
data:
  promtail.yaml: |
    client:
      backoff_config:
        ...
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: syslog
      static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/messages
      relabel_configs:
      - source_labels:
        - __path__
        target_label: filepath
    - job_name: kubernetes-pods-name
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: host
      - action: drop
        regex: ''
        source_labels:
        - __service__
    ...
```
config 분량이 너무 많아 불필요한 부분은 제거하는게 좋을 듯 하여, scrape_config를 하나 하나 뜯어보았고, 대략 override 내용 초안 잡아 작업 중입니다.
